export const listaConversaciones = [
  { nombreContacto: "Cliente 1", lastMessage: "Gracias", timeMessage: "18:45" },
  { nombreContacto: "Cliente 2", lastMessage: "Gracias", timeMessage: "18:44" },
  { nombreContacto: "Cliente 3", lastMessage: "Gracias", timeMessage: "18:45" },
  { nombreContacto: "Cliente 4", lastMessage: "Gracias", timeMessage: "18:45" },
];

export const listaMensajes = [
  {
    clienteID: 1,
    lastMessage: "Esta Perfecto, muchas gracias",
    timeLastMessage: "18:45",
    listaMensajes: [
      {
        personMessage: 2,
        message:
          "Buenas tardes como esta, me gustaría preguntar por el producto tanto",
        timeMessage: "18:45",
      },
      {
        personMessage: 2,
        message: "Todavia lo tiene disponible",
        timeMessage: "18:45",
      },
      {
        personMessage: 1,
        message: "Buenas noches, si, estaría a 100bs sin incluir envio",
        timeMessage: "18:45",
      },
      {
        personMessage: 2,
        message: "Y con envio cuantos sería",
        timeMessage: "18:45",
      },
      {
        personMessage: 2,
        message: "a la Av. Banzer 7mo anillo",
        timeMessage: "18:45",
      },
      {
        personMessage: 1,
        message: "Seria 10Bs",
        timeMessage: "18:45",
      },
      {
        personMessage: 2,
        message: "Esta Perfecto, muchas gracias",
        timeMessage: "18:45",
      },
      {
        personMessage: 2,
        message: "Esta Perfecto, muchas gracias",
        timeMessage: "18:45",
      },
      {
        personMessage: 2,
        message: "Esta Perfecto, muchas gracias",
        timeMessage: "18:45",
      },
      {
        personMessage: 2,
        message: "Esta Perfecto, muchas gracias",
        timeMessage: "18:45",
      },
      {
        personMessage: 2,
        message: "Esta Perfecto, muchas gracias",
        timeMessage: "18:45",
      },
      {
        personMessage: 2,
        message: "Esta Perfecto, muchas gracias",
        timeMessage: "18:45",
      },
      {
        personMessage: 2,
        message: "Esta Perfecto, muchas gracias",
        timeMessage: "18:45",
      },
      {
        personMessage: 2,
        message: "Esta Perfecto, muchas gracias",
        timeMessage: "18:45",
      },
      {
        personMessage: 2,
        message: "Esta Perfecto, muchas gracias",
        timeMessage: "18:45",
      },
      {
        personMessage: 2,
        message: "Esta Perfecto, muchas graciassssssssssssssssssssssss",
        timeMessage: "18:45",
      },
    ],
  },
  {
    clienteID: 2,
    listaMensajes: [
      {
        personMessage: 2,
        message: "Buenas noches a cuanto el promoción de invierno",
        timeMessage: "18:45",
      },
      {
        personMessage: 1,
        message: "El paquete está a 500Bs",
        timeMessage: "18:45",
      },
      {
        personMessage: 1,
        message: "Por la compra de dos, hay un 20% de descuento",
        timeMessage: "18:45",
      },
      {
        personMessage: 2,
        message: "Con uno estaría bien, gracias",
        timeMessage: "18:45",
      },
      {
        personMessage: 1,
        message: "Claro, el pago como desea realizar",
        timeMessage: "18:45",
      },
      {
        personMessage: 2,
        message: "Se puede por transferencia",
        timeMessage: "18:45",
      },
      {
        personMessage: 2,
        message: "O por QR también estaría bien",
        timeMessage: "18:45",
      },
    ],
  },
  {
    clienteID: 3,
    listaMensajes: [
      {
        personMessage: 2,
        message: "Vi en facebook que tiene a la venta tal producto",
        timeMessage: "18:45",
      },
      {
        personMessage: 2,
        message: "Quisiera saber el precio y en cuanto tiempo me lo entregan",
        timeMessage: "18:45",
      },
      {
        personMessage: 1,
        message: "Si, estaría a 100Bs, en 2 días se entrega",
        timeMessage: "18:45",
      },
      {
        personMessage: 2,
        message:
          "Estaría perfecto muchas gracias, hasta cuando le puedo confirmar",
        timeMessage: "18:45",
      },
      {
        personMessage: 1,
        message:
          "Hasta acabar stock, unos tres días mas estaría disponible yo creo",
        timeMessage: "18:45",
      },
      {
        personMessage: 1,
        message: "Me avisa cualquier cosa",
        timeMessage: "18:45",
      },
    ],
  },
  {
    clienteID: 4,
    listaMensajes: [
      {
        personMessage: 1,
        message: "Buenas tardes",
        timeMessage: "18:45",
      },
    ],
  },
  {
    clienteID: 5,
    listaMensajes: [
      {
        personMessage: 1,
        message: "Buenas tardes",
        timeMessage: "18:45",
      },
    ],
  },
  {
    clienteID: 6,
    listaMensajes: [
      {
        personMessage: 1,
        message: "Buenas tardes",
        timeMessage: "18:45",
      },
    ],
  },
];

export const listaInformacionClientes = [
  {
    clienteID: 1,
    nombre: "Cliente 1",
    telefono: 70005958,
    colorEtapa: "#3498DB",
    etapa: 1,
    etapaNombre: "Contacto Inicial",
    prioridadColor: "#F51D5C",
    prioridad: "Alta",
    probabilidad: "50%",
    categoriaColor: "#FB3088",
    categoria: 2,
    categoriaNombre: "Zapatos",
    cantidad: 5,
    ganancias: 50000,
  },
  {
    clienteID: 2,
    nombre: "Cliente 2",
    telefono: 70005958,
    colorEtapa: "#29C9C2",
    etapa: 2,
    etapaNombre: "Seguimiento",
    prioridadColor: "#1FCB71",
    prioridad: "Baja",
    probabilidad: "50%",
    categoriaColor: "#FB3088",
    categoria: 2,
    categoriaNombre: "Zapatos",
    cantidad: 5,
    ganancias: 50000,
  },
  {
    clienteID: 3,
    nombre: "Cliente 3",
    telefono: 70005958,
    colorEtapa: "#1CB68E",
    etapa: 2,
    etapaNombre: "Negociacion",
    prioridadColor: "#F5B31D",
    prioridad: "Media",
    probabilidad: "50%",
    categoriaColor: "#63C7FF",
    categoria: 1,
    categoriaNombre: "Ropa Femenina",
    cantidad: 5,
    ganancias: 50000,
  },
  {
    clienteID: 4,
    nombre: "Cliente 4",
    telefono: 70005958,
    colorEtapa: "#1CB68E",
    etapa: 2,
    etapaNombre: "Negociacion",
    prioridadColor: "#1FCB71",
    prioridad: "Baja",
    probabilidad: "50%",
    categoriaColor: "#675BFF",
    categoria: 3,
    categoriaNombre: "Ropa Masculina",
    cantidad: 5,
    ganancias: 50000,
  },
  {
    clienteID: 5,
    nombre: "Cliente 5",
    telefono: 70005958,
    colorEtapa: "#29C9C2",
    etapa: 2,
    etapaNombre: "Seguimiento",
    prioridadColor: "#F51D5C",
    prioridad: "Alta",
    probabilidad: "50%",
    categoriaColor: "#63C7FF",
    categoria: 1,
    categoriaNombre: "Zapatos",
    cantidad: 5,
    ganancias: 50000,
  },
  {
    clienteID: 6,
    nombre: "Juan",
    telefono: 78945612,
    colorEtapa: "#1CB68E",
    etapa: 3,
    etapaNombre: "Negociacion",
    prioridadColor: "#F51D5C",
    prioridad: "Alta",
    probabilidad: "50%",
    categoriaColor: "#675BFF",
    categoria: 3,
    categoriaNombre: "Ropa Masculina",
    cantidad: 5,
    ganancias: 50000,
  },
  {
    clienteID: 7,
    nombre: "Maria",
    telefono: 76543210,
    colorEtapa: "#27B563",
    etapa: 4,
    etapaNombre: "Vendido",
    prioridadColor: "#F5B31D",
    prioridad: "Media",
    probabilidad: "50%",
    categoriaColor: "#63C7FF",
    categoria: 1,
    categoriaNombre: "Zapatos",
    cantidad: 5,
    ganancias: 50000,
  },
  {
    clienteID: 8,
    nombre: "Jose",
    telefono: 70005958,
    colorEtapa: "#1CB68E",
    etapa: 3,
    etapaNombre: "Negociacion",
    prioridadColor: "#F51D5C",
    prioridad: "Alta",
    probabilidad: "50%",
    categoria: 2,
    categoriaColor: "#FB3088",
    categoriaNombre: "Ropa Femenina",
    cantidad: 5,
    ganancias: 50000,
  },
  {
    clienteID: 9,
    nombre: "Pedro",
    telefono: 60004848,
    colorEtapa: "#27B563",
    etapa: 4,
    etapaNombre: "Vendido",
    prioridadColor: "#F5B31D",
    prioridad: "Media",
    probabilidad: "50%",
    categoriaColor: "#A1EA22",
    categoria: 4,
    categoriaNombre: "Accesorios",
    cantidad: 5,
    ganancias: 50000,
  },
  {
    clienteID: 10,
    nombre: "Nancy",
    telefono: 60020351,
    colorEtapa: "#29C9C2",
    etapa: 2,
    etapaNombre: "Seguimiento",
    prioridadColor: "#F5B31D",
    prioridad: "Media",
    probabilidad: "50%",
    categoriaColor: "#A1EA22",
    categoria: 4,
    categoriaNombre: "Accesorios",
    cantidad: 5,
    ganancias: 50000,
  },
  {
    clienteID: 11,
    nombre: "Cliente 11",
    telefono: 60005958,
    colorEtapa: "#3498DB",
    etapa: 1,
    etapaNombre: "Contacto Inicial",
    prioridadColor: "#F5B31D",
    prioridad: "Media",
    probabilidad: "50%",
    categoriaColor: "gray",
    categoria: 5,
    categoriaNombre: "Sin Categoría",
    cantidad: 5,
    ganancias: 50000,
  },
];

export const listaClientes = [
  {
    clienteID: 1,
    clienteNombre: "Maria Jose",
    telefono: "70005958",
    email: "mjso0308@gmail.com",
    categoria: "Ropa Femenina",
    prioridad: "Media",
    etapa: "Negociacion",
    colorEtapa: "#1CB68E",
    colorCategoria: "#63C7FF",
    prioridadColor: "red",
  },
  {
    clienteID: 2,
    clienteNombre: "Juan SC",
    telefono: "78965412",
    email: "juan_sc@gmail.com",
    categoria: "Accesorios",
    prioridad: "Alta",
    etapa: "Negociacion",
    colorEtapa: "#1CB68E",
    colorCategoria: "#A1EA22",
    prioridadColor: "red",
  },
  {
    clienteID: 3,
    clienteNombre: "Luciana LP",
    telefono: "60045480",
    email: "luciana_lp@gmail.com",
    categoria: "Zapatos",
    prioridad: "Alta",
    etapa: "Seguimiento",
    colorEtapa: "#29C9C2",
    colorCategoria: "#675BFF",
    prioridadColor: "red",
  },
  {
    clienteID: 4,
    clienteNombre: "+591 71234567",
    telefono: "71234567",
    email: "",
    categoria: "Sin Categoría",
    prioridad: "Media",
    etapa: "Contacto inicial",
    colorEtapa: "#3498DB",
    colorCategoria: "gray",
    prioridadColor: "red",
  },
  {
    clienteID: 5,
    clienteNombre: "Carlos CBBA",
    telefono: "60000000",
    email: "juan_sc@gmail.com",
    categoria: "Ropa Masculina",
    prioridad: "Alta",
    etapa: "Negociacion",
    colorEtapa: "#1CB68E",
    colorCategoria: "#FB3088",
    prioridadColor: "red",
  },
  {
    clienteID: 6,
    clienteNombre: "Camila SC",
    telefono: "78965412",
    email: "juan_sc@gmail.com",
    categoria: "Accesorios",
    prioridad: "Alta",
    etapa: "Negociacion",
    colorEtapa: "#1CB68E",
    colorCategoria: "#A1EA22",
    prioridadColor: "red",
  },
];
export const listaFiltroClientes = [
  { tipo: 0, filtro: "Ninguno" },
  { tipo: 1, filtro: "Por Categoría" },
  { tipo: 2, filtro: "Por Etapa" },
  { tipo: 3, filtro: "Por Prioridad" },
];
export const listaPrioridades = [
  { prioridad: "Alta", nombre: "Prioridad Alta", color: "#F51D5C" },
  { prioridad: "Media", nombre: "Prioridad Media", color: "#F5B31D" },
  { prioridad: "Baja", nombre: "Prioridad Baja", color: "#1FCB71" },
];
export const listaEtapas = [
  { etapa: 1, nombre: "Contacto Inicial", color: "#3498DB" },
  { etapa: 2, nombre: "Seguimiento", color: "#29C9C2" },
  { etapa: 3, nombre: "Negociacion", color: "#1CB68E" },
  { etapa: 4, nombre: "Vendido", color: "#27B563" },
];
export const listaOpciones = [
  { titulo: "CONVERSACIONES", opcion: 1, ruta: "/conversaciones" },
  { titulo: "ITEMS", opcion: 2, ruta: "/items" },
  { titulo: "CLIENTES", opcion: 3, ruta: "/clientes" },
  { titulo: "VENTAS", opcion: 4, ruta: "/ventas" },
  { titulo: "MENSAJES RÁPIDOS", opcion: 5, ruta: "/mensajes-rapidos" },
  { titulo: "INTEGRANTES", opcion: 6, ruta: "/integrantes" },
  { titulo: "TAREAS", opcion: 7, ruta: "/tareas" },
];
export const listaItems = [
  {
    itemID: 1,
    nombre: "Item 1",
    descripcion: "Descripcion 1",
    precio: 40,
    moneda: "Bs",
    disponibilidad: true,
    montoVendido: 200,
    cantidadVendida: 5,
    cantidadCotizada: 10,
  },
  {
    itemID: 2,
    nombre: "Item 2",
    descripcion: "Descripcion 2",
    precio: 20,
    moneda: "Bs",
    disponibilidad: true,
    montoVendido: 300,
    cantidadVendida: 15,
    cantidadCotizada: 20,
  },
  {
    itemID: 3,
    nombre: "Item 3",
    descripcion: "Descripcion 3",
    precio: 15,
    disponibilidad: true,
    moneda: "Bs",
    montoVendido: 150,
    cantidadVendida: 10,
    cantidadCotizada: 30,
  },
  {
    itemID: 4,
    nombre: "Item 4",
    descripcion: "Descripcion 4",
    precio: 35,
    disponibilidad: true,
    moneda: "Bs",
    montoVendido: 350,
    cantidadVendida: 10,
    cantidadCotizada: 30,
  },
];
export const listaTareas = [
  {
    tareaID: 1,
    descripcion: "Recoger manteles y platos de Doña Juanita",
    cliente_id: 1,
    cliente_nombre: "Cliente 1",
    fecha_fin: "20/12/2023",
  },
  {
    tareaID: 2,
    descripcion: "Comprar mas sillas para alquilar",
    cliente_id: 0,
    cliente_nombre: "",
    fecha_fin: "21/12/2023",
  },
  {
    tareaID: 3,
    descripcion: "Item 3",
    cliente_id: "Entregar 200 mesas en la zona Norte",
    cliente_nombre: "Descripcion 3",
    fecha_fin: "24/12/2023",
  },
];
export const listaIntegrantes = [
  {
    integranteID: 1,
    nombre: "Juan Perez",
    cargo: "Administrador",
    correo: "jperez@gmail.com",
    telefono: "70005958",
  },
  {
    integranteID: 2,
    nombre: "Carla Fernandez",
    cargo: "Gerente de Ventas",
    correo: "cfernandez@gmail.com",
    telefono: "60004948",
  },
  {
    integranteID: 3,
    nombre: "Pedro Martinez",
    cargo: "Pasante de Ventas",
    correo: "pmartinez@gmail.com",
    telefono: "70056585",
  },
  {
    integranteID: 4,
    nombre: "Gonzalo Villarroel",
    cargo: "Encargado Call Center",
    correo: "gvillarroel@gmail.com",
    telefono: "65202220",
  },
];

export const listaConversacionesc = [
  {
    conversacionID: 1,
    cliente: "Cliente 1",
    estado: "En Espera",
    etapa: "Etapa 1",
    mensaje: "Mensaje 1",
    producto: "Producto 1",
  },
  {
    conversacionID: 2,
    cliente: "Cliente 2",
    estado: "En Espera",
    etapa: "Etapa 2",
    mensaje: "Mensaje 2",
    producto: "Producto 2",
  },
  {
    conversacionID: 3,
    cliente: "Cliente 3",
    estado: "En Espera",
    etapa: "Etapa 3",
    mensaje: "Mensaje 3",
    producto: "Producto 3",
  },
  {
    conversacionID: 4,
    cliente: "Cliente 4",
    estado: "Por Responder",
    etapa: "Etapa 4",
    mensaje: "Mensaje 4",
    producto: "Producto 4",
  },
  {
    conversacionID: 5,
    cliente: "Cliente 5",
    estado: "En Espera",
    etapa: "Etapa 1",
    mensaje: "Mensaje 5",
    producto: "Producto 5",
  },
  {
    conversacionID: 6,
    cliente: "Cliente 6",
    estado: "Por Responder",
    etapa: "Etapa 3",
    mensaje: "Mensaje 6",
    producto: "Producto 6",
  },
  {
    conversacionID: 7,
    cliente: "Cliente 7",
    estado: "En Espera",
    etapa: "Etapa 2",
    mensaje: "Mensaje 7",
    producto: "Producto 7",
  },
  {
    conversacionID: 8,
    cliente: "Cliente 8",
    estado: "En Espera",
    etapa: "Etapa 1",
    mensaje: "Mensaje 1",
    producto: "Producto 1",
  },
  {
    conversacionID: 9,
    cliente: "Cliente 9",
    estado: "En Espera",
    etapa: "Etapa 2",
    mensaje: "Mensaje 9",
    producto: "Producto 9",
  },
];

export const listaCategorias = [
  {
    nombre: "Ropa Femenina",
    categoria: 1,
    color: "#63C7FF",
    cantidadClientes: 2,
    cantidadGanancias: 10000,
  },
  {
    nombre: "Ropa Masculina",
    color: "#FB3088",
    categoria: 2,
    cantidadClientes: 4,
    cantidadGanancias: 50000,
  },
  {
    nombre: "Zapatos",
    color: "#675BFF",
    categoria: 3,
    cantidadClientes: 7,
    cantidadGanancias: 70000,
  },
  {
    nombre: "Accesorios",
    color: "#A1EA22",
    categoria: 4,
    cantidadClientes: 10,
    cantidadGanancias: 30000,
  },
  {
    nombre: "Sin categoria",
    categoria: 5,
    color: "gray",
    cantidadClientes: 2,
    cantidadGanancias: 10000,
  },
];
